image: microsoft/dotnet:2.1.300-preview2-sdk-alpine

stages:
  - dotnet

build:
  stage: dotnet
  script:
    - dotnet restore
    - dotnet build
    - dotnet test --no-restore --verbosity normal --no-build Build.Tests --framework net6.0
