//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyInformationalVersionAttribute("v1.0.0.19-build-00015-236-gbb5c882-dirty-")]

// Generated by the MSBuild WriteCodeFragment class.

