version: 2.1
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/dcb2d72c9dad83a95777
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12
    steps:
      - run: apk --no-cache add curl unzip
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Build.Tests
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud