version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.104-sdk-alpine3.8
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Build.Tests